name: Build Containers

on:
  schedule:
    # Runs every Sunday at 6am
    - cron: '0 6 * * 0'
  workflow_dispatch: # Enables manual trigger from GitHub UI

jobs:
  # Node latest, Python 3+Pip latest, FFMpeg 6.1.2 with CUDA support (x64)
  node-python-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: node-python-ffmpeg
          platforms: linux/amd64
          push: true
          tags: mayanklahiri/node-python-ffmpeg:latest
          cache-from: type=registry,ref=mayanklahiri/node-python-ffmpeg:buildcache
          cache-to: type=registry,ref=mayanklahiri/node-python-ffmpeg:buildcache,mode=max
